### ISSUE TITLE
DB2 for i interface with Athena

### ISSUE THREAD

**Issue by brunocl-kyndryl** [aws-samples/aws-lambda-interface-for-db2-i#1]
Hello! I am testing some connectivity between Athena and IBM i (aka AS400). Is this lambda function compatible with Athena? I've successfully deployed this function but it fails with Task Timed Out in Athena.

**Comment by linbasil** [comment]
The Lambda function serves as a generic interface for IBM i. Integration with most data sources is possible, but your implementation will vary. The provided code has examples of queries to IBM i, but integration with any other components (in your case Athena) will largely depend on what you are trying to do / how you want to integrate

**Comment by brunocl-kyndryl** [comment]
@linbasil  Thanks for replying back. We are looking for performing some simple queries in IBM i database using Athena but it fails with task timed out when retrieving database information in Athena's console and I don't even see connections coming from Athena to IBM i which makes me think it is failing before communication starts. Could you please advise?
In parallel, I am trying using AWS DB2 connector but getting different errors.

**Comment by linbasil** [comment]
I cannot speak for Athena connectivity, but I can help with the DB2 interface given more details. For example,

- Where is the Lambda function deployed? 
- Have you verified network connectivity between your environment and Db2?
- How is the Lambda function invoked?
- Have you already written your queries within the Db2 interface?
- Which errors are you receiving?

**Comment by brunocl-kyndryl** [comment]
Where is the Lambda function deployed? Not sure what that means. Could you please clarify?
Have you verified network connectivity between your environment and Db2? Yes, a VM instance in the same subnet is able to reach out to the DB2 for i hosted on premise.
How is the Lambda function invoked? Lambda function is invoked by Athena through its interface. At this point, no query is performed.
Have you already written your queries within the Db2 interface? No, the queries are written in Athena's console once connection is stablished.
Which errors are you receiving? Task time out. No other information is gives that helps identify the error.

**Comment by brunocl-kyndryl** [comment]
Let me try to better explain how it is setup:

1. I've deployed the ECR and Lambda functions using deploy scripts.
2. I configured a data source in Athena pointing to the lambda function.
3. In Athena's query editor, when I select the data source associated with lambda function, it tries to retrieve database information (before I can even run a query) but fails with Tasked time out. These are the messages in CloudWatch:
![image](https://user-images.githubusercontent.com/107867604/228365680-10bb98b9-dc06-402c-a21d-7c1a0e497fea.png)

**Comment by brunocl-kyndryl** [comment]
@linbasil I spoke to AWS support who found the error happened because of endpoint setup to secret manager. After fixing it, I got anothe errors:

"Failed to invoke lambda function due to com.amazonaws.services.lambda.model.TooManyRequestsException: Rate Exceeded. (Service: AWSLambda; Status Code: 429; Error Code: TooManyRequestsException; Request ID: 8ee4504d-9e2c-431c-9844-28d7f51bd02f; Proxy: null)"

**Comment by linbasil** [comment]
I think there may be a misunderstanding in the usage of this repo. This repo allows you to make connections to Db2 from Lambda, but the query logic is still left up to the developer to implement.

It does not act as a pure connector between a source and a target, which seems like what you are trying to accomplish with Athena, but AWS provides [documentation](https://docs.aws.amazon.com/athena/latest/ug/connect-data-source-federation-sdk.html) for implementing this. It's certainly a useful feature, and I'd be happy to incorporate any changes you make to expand this functionality.

Lastly, you have a `TooManyRequestsException`, which means that the deployed Lambda function is being invoked too often. I would disconnect the Lambda trigger from Athena, and work on invoking the Lambda function with test events to verify connectivity with Db2 prior to connecting a trigger. For more information, see the [blog post](https://repost.aws/knowledge-center/lambda-troubleshoot-throttling).
