### ISSUE TITLE
Trying to connect to a DB2 AS400 deployment

### ISSUE THREAD

**Issue by bryanrussel-corona** [aws-samples/aws-lambda-interface-for-db2-i#3]
I was instructed to test this solution as an interface for a DB2 as400 deployment on premise. I have done the networking for this and managed to telnet to the db2 server im supposed to connect to. Now im still getting this error code i pasted here. For usage ive deployed the lambda manually but i built the container from the docker file included. ive also incorporated the latest driver. can you help if this solution is compatible and if it is viable. For other context i havent changed the logic of the main.py yet aside from manually inputting the credentials via code since were still have problems settings up secrets manager. 

driver version: ibm-iaccess-1.1.0.27-1.0.x86_64

error: "errorMessage": "('08S01', '[08S01]

CWBNL0202 - cwbodmsg.dllCWBNL0202 - cwbodmsg.dllCWBNL0202 - cwbodmsg.dll comm rc=11001 - CWBNL0202 - cwbcomsg.dll

**Comment by lordjabez** [comment]
What version of Db2 are you trying to connect to? Is SSL enabled on connections?

`08S01` is a connection error of some form [based on what I see in the IBM docs](https://www.ibm.com/docs/en/db2/11.5?topic=messages-sqlstate#rsttmsg__code08).

Are you certain the Lambda itself has proper network connectivity to the database? You mentioned telnet. Where did you run that from? Could you invoke the docker image from that location and do a test? This smells like a networking error of some kind.

**Comment by bryanrussel-corona** [comment]
It does look like networking. Im currently checking lambda's network connectivity since this might be a port issue. telnet was allowed on the port that allows telnet but lambda uses a different port since it uses an ODBC driver.
